import sqlmodel

"""updated table fields

Revision ID: d8d999eb4f6f
Revises: 7871d3181179
Create Date: 2024-06-27 09:49:24.592170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8d999eb4f6f'
down_revision: Union[str, None] = '7871d3181179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
